# backend/.pre-commit-config.yaml
repos:

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: clean-pycache
        name: Clean Pycache
        entry: bash -c 'find . -name "__pycache__" -type d -exec rm -r {} + && find . -name "*.pyc" -type f -delete'
        language: system
        pass_filenames: false

      - id: docker-pytest
        name: Run pytest inside Docker
        entry: docker exec study-buddy-backend-dev poetry run pytest
        language: system
        pass_filenames: false

      - id: docker-mypy
        name: Run mypy inside Docker
        entry: docker exec study-buddy-backend-dev poetry run mypy app
        language: system
        pass_filenames: false