# backend/.pre-commit-config.yaml
repos:

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.7.0
  #   hooks:
  #     - id: mypy
  #       args: ["--explicit-package-bases", "--config-file=mypy.ini"]

  # - repo: local
  #   hooks:
  #     - id: run-pytest
  #       name: Run Pytest (backend)
  #       entry: poetry run pytest
  #       language: system
  #       pass_filenames: false
  #       types: [python]