"""Using page_numbers and sections instead of a single one for each

Revision ID: b4d6d88f5330
Revises: d2f82a2381ff
Create Date: 2025-06-27 16:31:44.188777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d6d88f5330'
down_revision: Union[str, None] = 'd2f82a2381ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_chunks', sa.Column('page_numbers', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('file_chunks', sa.Column('sections', sa.ARRAY(sa.Text()), nullable=True))
    op.drop_column('file_chunks', 'section')
    op.drop_column('file_chunks', 'page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_chunks', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('file_chunks', sa.Column('section', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('file_chunks', 'sections')
    op.drop_column('file_chunks', 'page_numbers')
    # ### end Alembic commands ###
