"""filename to file chunk

Revision ID: c13c2f8d96cb
Revises: b4d6d88f5330
Create Date: 2025-06-28 03:24:45.568830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13c2f8d96cb'
down_revision: Union[str, None] = 'b4d6d88f5330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_chunks', sa.Column('file_name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_chunks', 'file_name')
    # ### end Alembic commands ###
