"""more chunk metadata

Revision ID: d2cd82a2b7af
Revises: fed321b898fa
Create Date: 2025-05-25 04:24:40.889445

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2cd82a2b7af"
down_revision: Union[str, None] = "fed321b898fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_chunks", sa.Column("content_type", sa.Text(), nullable=True))
    op.add_column("file_chunks", sa.Column("end_time", sa.Float(), nullable=True))
    op.add_column("file_chunks", sa.Column("page_number", sa.Integer(), nullable=True))
    op.add_column("file_chunks", sa.Column("start_time", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_chunks", "start_time")
    op.drop_column("file_chunks", "page_number")
    op.drop_column("file_chunks", "end_time")
    op.drop_column("file_chunks", "content_type")
    # ### end Alembic commands ###
