"""rename file source to content_type

Revision ID: d2f82a2381ff
Revises: d2cd82a2b7af
Create Date: 2025-06-26 04:50:51.388033

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2f82a2381ff"
down_revision: Union[str, None] = "d2cd82a2b7af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column("files", "source", new_column_name="content_type")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files", sa.Column("source", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("files", "content_type")
    # ### end Alembic commands ###
